################## 📒 RECIPES ROUTES #######################

#### Get all recipes
GET http://localhost:3000/recipes

#### Get one recipe by ID
GET http://localhost:3000/recipes/68410a64341d7f693ce9c4cf

#### Create new recipe
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "name": "Oatmeal Pancakes",
  "ingredients": ["oats", "egg", "ripe banana", "milk", "cinnamon"],
  "instructions": "Blend all ingredients. Cook on a nonstick pan on both sides until golden. Serve with fruit or honey.",
  "category": "Breakfast",
  "prepTime": 5,
  "cookTime": 10,
  "imageUrl": "https://cookieandkate.com/images/2021/04/blender-pancakes-recipe-1.jpg"
}


#### Update recipe by ID
PUT http://localhost:3000/recipes/684114556919c8aa4ada910a
Content-Type: application/json

{
  "name": "Oatmeal Pancakes",
    "ingredients": [
      "oats",
      "ripe banana",
      "milk",
      "cinnamon"
    ],
    "instructions": "Blend all ingredients. Cook on a nonstick pan on both sides until golden. Serve with fruit or honey.",
    "category": "Breakfast",
    "prepTime": 5,
    "cookTime": 10,
    "imageUrl": "https://cookieandkate.com/images/2021/04/blender-pancakes-recipe-1.jpg"
}

#### Delete recipe by ID
DELETE http://localhost:3000/recipes/68410cdf341d7f693ce9c4da




################## 👤 USERS ROUTES  ###########################

### Get all users
GET http://localhost:3000/users

### Get one user by ID
GET http://localhost:3000/users/684115626919c8aa4ada910c

### Create new user
POST http://localhost:3000/users
Content-Type: application/json


{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "securePass123",
  "favorites": [],
  "role": "user",
  "bio": "Loves quick and healthy meals."
}

### Update user by ID
PUT http://localhost:3000/users/6841158d6919c8aa4ada9110
Content-Type: application/json

{
    "_id": "6841158d6919c8aa4ada9110",
    "username": "greenveggie",
    "email": "veggie@example.com",
    "password": "plantBasedLife",
    "favorites": ["684114556919c8aa4ada910a"],
    "role": "user",
    "bio": "Nutritionist focused on plant-based meals."
  }

### Delete user by ID
DELETE http://localhost:3000/users/
